### ISSUE TITLE
[Update] Change loading image for items in collection search

### ISSUE THREAD

**Issue by sauravhiremath** [sauravhiremath/fifa#19]
## Current

![image](https://user-images.githubusercontent.com/28642011/94834902-9a613280-042e-11eb-98f6-9ee51f73a5c4.png)

## Reasons

- It is ugly
- Clunky animation and consumes too much bandwidth

**Comment by khushishikhu** [comment]
may i work on this

**Comment by sauravhiremath** [comment]
Yeah sure go for it 👍

**Comment by sauravhiremath** [comment]
fixed
